### ISSUE TITLE
Finish writing unit tests for Chip8 instructions

### ISSUE THREAD

**Issue by Taiters** [Taiters/chip8-web#10]
It would be good to finish the unit tests for the instructions. These tests have been started, so existing tests can be used as a guide.

The Chip8 instructions can be viewed [here](http://mattmik.com/files/chip8/mastering/chip8.html)

The current tests can be viewed [here](https://github.com/Taiters/chip8-web/blob/master/tests/cpu/instructions.test.js) and the instruction implementations are [here](https://github.com/Taiters/chip8-web/blob/master/src/cpu/instructions/operations.js).

As far as unit tests go these should be pretty straightforward, as we can just pass in a state, and assert on the values of the returned state.

Happy to answer any questions!

**Comment by nimvb** [comment]
@Taiters Could you please check the [pull request](#111) that I submitted for the issue?
