### ISSUE TITLE
Wrong value for the shown for the sound timer

### ISSUE THREAD

**Issue by Taiters** [Taiters/chip8-web#11]
**Describe the bug**
The display for the **sound** timer (shown as the ST value in the UI) always matches the **delay** timer (shown as the DT value in the UI)

**To Reproduce**
The easiest way to reproduce is to run the delay timer test ROM and observe the fields.
1. Run this ROM (Delay timer test): https://github.com/dmatlack/chip8/blob/master/roms/programs/Delay%20Timer%20Test%20%5BMatthew%20Mikolay%2C%202010%5D.ch8
2. Observe the ST field always matches the DT field

**Expected behavior**
The ST field should show the value for the **sound** timer, not the **delay** timer.

**Additional context**
The component which renders these fields can be found [here](https://github.com/Taiters/chip8-web/blob/master/src/components/cpuInfo.js)

**Comment by flurmbo** [comment]
Can I work on this one?

**Comment by Taiters** [comment]
Sure @flurmbo!

**Comment by flurmbo** [comment]
Hey @Taiters, I think the problem is that in cpuInfo.js the ST field is set to display props.cpu.delay instead of props.cpu.sound. However, I am unable to confirm this because both the ST and DT field stay at zero when I run the delay timer test ROM. What behavior should I be seeing?

**Comment by Taiters** [comment]
Hey @flurmbo, yeah looks like that's the issue.

Yeah it's hard to confirm the fix, I've been struggling to find ROMs which use the sound timer as well. I'm happy for us to fix this UI issue for now, and I can finish the unit tests for the instructions soon to increase the confidence there (An issue for this is already open).

**Comment by flurmbo** [comment]
Ok @Taiters, I'll go ahead and make a pull request for this fix
