### ISSUE TITLE
Tidy up the UI for the instruction list

### ISSUE THREAD

**Issue by Taiters** [Taiters/chip8-web#6]
The current instruction list simply displays the string representation for each instruction and its address. It would be nice to add some improved styling to this so they are easier to read. Even just highlighting each separate row and making the address text a little smaller than the instruction could be a nice start.

Happy to discuss different approaches and ideas.

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/3321476/46583975-c91dbb80-ca55-11e8-88bc-f4ed91c4ac74.png">

**Comment by Bharat23** [comment]
I can pick this up!

**Comment by Taiters** [comment]
Great, thanks @Bharat23! Let me know if you have any questions.

**Comment by farmanp** [comment]
@Bharat23 I'm interested in seeing how you handle this - can you share your progress?
