### ISSUE TITLE
Add a "Help" screen

### ISSUE THREAD

**Issue by Taiters** [Taiters/chip8-web#9]
Add a help screen which displays information about how to use the emulator. This could include

* The key bindings (Which can be found in the [keyboard.js](https://github.com/Taiters/chip8-web/blob/master/src/cpu/keyboard.js) file)
* Where to find ROMs

This could potentially be accessible via a clickable help icon which opens a modal, or an entirely separate page. Happy to discuss.

**Comment by arminderk** [comment]
Hey @Taiters, just saw your issue. Would be interested in working on it. How did you want to approach this? Is the info. going to be really long, or short? I guess that would determine the use of a modal or separate page

**Comment by Taiters** [comment]
Hey @arminderk. Thanks for taking a look!

I don't think there needs to be a huge amount of information on it. The main information it requires is the key bindings and possibly a link to a source of ROMs (Such as https://github.com/dmatlack/chip8/tree/master/roms)

*Ideally* the rest of the UI should be easy enough to use to avoid the need for explanations in the help page.

**Comment by arminderk** [comment]
Hey @Taiters, I was thinking of using react-bootstrap to load the modal. Are you okay with third-party style libraries or do you prefer custom styling? I thought that it may easier to incorporate bootstrap and modal.

**Comment by Taiters** [comment]
Hey @arminderk, yeah using bootstrap sounds good.
